packages:
  - apps/admin
  - apps/web

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#7301b75bde57f3fabf3e26a41617644d46b36ced&path:packages/auth-api
