packages:
  - apps/admin
  - apps/web

allowBuilds:
  esbuild: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#669aaed83252c6a1019a3dbabfe5e5bda2c9664f&path:packages/auth-api
