packages:
  - apps/admin
  - apps/web

allowBuilds:
  esbuild: true
  vue-demi: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - vite@8.2.2
overrides:
  '@novelia/auth-api': github:auto-novel/auth#e6909c2711d3e13c2da8a7d27505f3dc0880e24e&path:packages/auth-api
