//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Comment struct {
	ID             int64 `sql:"primary_key"`
	SubjectType    int16
	SubjectID      int64
	RootID         *int64 // NULL=一级评论；非 NULL=子回复所属的一级根评论 ID
	Content        string
	AuthorID       int64
	AuthorUsername string
	Status         int16 // 评论状态: 0=published, 1=hidden, 2=deleted
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Attr           string
}
