//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Post struct {
	ID             int64 `sql:"primary_key"`
	CategoryID     int64
	Title          string
	AuthorID       int64
	AuthorUsername string
	Content        string
	Status         int16  // 帖子状态: 0=published, 1=hidden, 2=deleted
	ViewsCount     int32  // 帖子详情页成功加载的累计次数，每次加载计 1 次
	CommentsCount  int32  // 帖子下 status=published 的评论数量，统计一级评论和子回复
	CommentsLocked bool   // true=评论区锁定状态，禁止新增评论；false=评论区开放状态，可新增评论
	PinOrder       *int32 // NULL=普通帖；非NULL=置顶帖的排序优先级，数值越小越靠前
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ActiveAt       time.Time // 帖子最后活跃时间；产生有效新评论等活跃事件时由应用层更新，用于列表排序
	Attr           string
}
