//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tag struct {
	ID         int64 `sql:"primary_key"`
	CategoryID int64
	Name       string
	Color      int16 // 预定义颜色的编号
	IsActive   bool  // true=可用于新帖绑定；false=停止新增绑定
	SortOrder  int32 // 标签展示顺序，数值越小越靠前
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Attr       string
}
