//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Comment = newCommentTable("public", "comment", "")

type commentTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	SubjectType    postgres.ColumnInteger
	SubjectKey     postgres.ColumnString
	RootID         postgres.ColumnInteger // NULL=一级评论；非 NULL=子回复所属的一级根评论 ID
	Content        postgres.ColumnString
	AuthorID       postgres.ColumnInteger
	AuthorUsername postgres.ColumnString
	Status         postgres.ColumnInteger // 评论状态: 0=published, 1=hidden, 2=deleted
	CreatedAt      postgres.ColumnTimestampz
	UpdatedAt      postgres.ColumnTimestampz
	Attr           postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CommentTable struct {
	commentTable

	EXCLUDED commentTable
}

// AS creates new CommentTable with assigned alias
func (a CommentTable) AS(alias string) *CommentTable {
	return newCommentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CommentTable with assigned schema name
func (a CommentTable) FromSchema(schemaName string) *CommentTable {
	return newCommentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CommentTable with assigned table prefix
func (a CommentTable) WithPrefix(prefix string) *CommentTable {
	return newCommentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CommentTable with assigned table suffix
func (a CommentTable) WithSuffix(suffix string) *CommentTable {
	return newCommentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCommentTable(schemaName, tableName, alias string) *CommentTable {
	return &CommentTable{
		commentTable: newCommentTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCommentTableImpl("", "excluded", ""),
	}
}

func newCommentTableImpl(schemaName, tableName, alias string) commentTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		SubjectTypeColumn    = postgres.IntegerColumn("subject_type")
		SubjectKeyColumn     = postgres.StringColumn("subject_key")
		RootIDColumn         = postgres.IntegerColumn("root_id")
		ContentColumn        = postgres.StringColumn("content")
		AuthorIDColumn       = postgres.IntegerColumn("author_id")
		AuthorUsernameColumn = postgres.StringColumn("author_username")
		StatusColumn         = postgres.IntegerColumn("status")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		AttrColumn           = postgres.StringColumn("attr")
		allColumns           = postgres.ColumnList{IDColumn, SubjectTypeColumn, SubjectKeyColumn, RootIDColumn, ContentColumn, AuthorIDColumn, AuthorUsernameColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn, AttrColumn}
		mutableColumns       = postgres.ColumnList{SubjectTypeColumn, SubjectKeyColumn, RootIDColumn, ContentColumn, AuthorIDColumn, AuthorUsernameColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn, AttrColumn}
		defaultColumns       = postgres.ColumnList{StatusColumn, CreatedAtColumn, UpdatedAtColumn, AttrColumn}
	)

	return commentTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		SubjectType:    SubjectTypeColumn,
		SubjectKey:     SubjectKeyColumn,
		RootID:         RootIDColumn,
		Content:        ContentColumn,
		AuthorID:       AuthorIDColumn,
		AuthorUsername: AuthorUsernameColumn,
		Status:         StatusColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		Attr:           AttrColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
