//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PostFavorite = newPostFavoriteTable("public", "post_favorite", "")

type postFavoriteTable struct {
	postgres.Table

	// Columns
	PostID    postgres.ColumnInteger
	UserID    postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PostFavoriteTable struct {
	postFavoriteTable

	EXCLUDED postFavoriteTable
}

// AS creates new PostFavoriteTable with assigned alias
func (a PostFavoriteTable) AS(alias string) *PostFavoriteTable {
	return newPostFavoriteTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostFavoriteTable with assigned schema name
func (a PostFavoriteTable) FromSchema(schemaName string) *PostFavoriteTable {
	return newPostFavoriteTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostFavoriteTable with assigned table prefix
func (a PostFavoriteTable) WithPrefix(prefix string) *PostFavoriteTable {
	return newPostFavoriteTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostFavoriteTable with assigned table suffix
func (a PostFavoriteTable) WithSuffix(suffix string) *PostFavoriteTable {
	return newPostFavoriteTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostFavoriteTable(schemaName, tableName, alias string) *PostFavoriteTable {
	return &PostFavoriteTable{
		postFavoriteTable: newPostFavoriteTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newPostFavoriteTableImpl("", "excluded", ""),
	}
}

func newPostFavoriteTableImpl(schemaName, tableName, alias string) postFavoriteTable {
	var (
		PostIDColumn    = postgres.IntegerColumn("post_id")
		UserIDColumn    = postgres.IntegerColumn("user_id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{PostIDColumn, UserIDColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return postFavoriteTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PostID:    PostIDColumn,
		UserID:    UserIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
