//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Post = newPostTable("public", "post", "")

type postTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	CategoryID     postgres.ColumnInteger
	Title          postgres.ColumnString
	AuthorID       postgres.ColumnInteger
	AuthorUsername postgres.ColumnString
	Content        postgres.ColumnString
	Status         postgres.ColumnInteger // 帖子状态: 0=published, 1=hidden, 2=deleted
	ViewsCount     postgres.ColumnInteger // 帖子详情页成功加载的累计次数，每次加载计 1 次
	CommentsCount  postgres.ColumnInteger // 帖子下 status=published 的评论数量，统计一级评论和子回复
	CommentsLocked postgres.ColumnBool    // true=评论区锁定状态，禁止新增评论；false=评论区开放状态，可新增评论
	PinOrder       postgres.ColumnInteger // NULL=普通帖；非NULL=置顶帖的排序优先级，数值越小越靠前
	CreatedAt      postgres.ColumnTimestampz
	UpdatedAt      postgres.ColumnTimestampz
	ActiveAt       postgres.ColumnTimestampz // 帖子最后活跃时间；产生有效新评论等活跃事件时由应用层更新，用于列表排序
	Attr           postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PostTable struct {
	postTable

	EXCLUDED postTable
}

// AS creates new PostTable with assigned alias
func (a PostTable) AS(alias string) *PostTable {
	return newPostTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostTable with assigned schema name
func (a PostTable) FromSchema(schemaName string) *PostTable {
	return newPostTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostTable with assigned table prefix
func (a PostTable) WithPrefix(prefix string) *PostTable {
	return newPostTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostTable with assigned table suffix
func (a PostTable) WithSuffix(suffix string) *PostTable {
	return newPostTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostTable(schemaName, tableName, alias string) *PostTable {
	return &PostTable{
		postTable: newPostTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newPostTableImpl("", "excluded", ""),
	}
}

func newPostTableImpl(schemaName, tableName, alias string) postTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		CategoryIDColumn     = postgres.IntegerColumn("category_id")
		TitleColumn          = postgres.StringColumn("title")
		AuthorIDColumn       = postgres.IntegerColumn("author_id")
		AuthorUsernameColumn = postgres.StringColumn("author_username")
		ContentColumn        = postgres.StringColumn("content")
		StatusColumn         = postgres.IntegerColumn("status")
		ViewsCountColumn     = postgres.IntegerColumn("views_count")
		CommentsCountColumn  = postgres.IntegerColumn("comments_count")
		CommentsLockedColumn = postgres.BoolColumn("comments_locked")
		PinOrderColumn       = postgres.IntegerColumn("pin_order")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampzColumn("updated_at")
		ActiveAtColumn       = postgres.TimestampzColumn("active_at")
		AttrColumn           = postgres.StringColumn("attr")
		allColumns           = postgres.ColumnList{IDColumn, CategoryIDColumn, TitleColumn, AuthorIDColumn, AuthorUsernameColumn, ContentColumn, StatusColumn, ViewsCountColumn, CommentsCountColumn, CommentsLockedColumn, PinOrderColumn, CreatedAtColumn, UpdatedAtColumn, ActiveAtColumn, AttrColumn}
		mutableColumns       = postgres.ColumnList{CategoryIDColumn, TitleColumn, AuthorIDColumn, AuthorUsernameColumn, ContentColumn, StatusColumn, ViewsCountColumn, CommentsCountColumn, CommentsLockedColumn, PinOrderColumn, CreatedAtColumn, UpdatedAtColumn, ActiveAtColumn, AttrColumn}
		defaultColumns       = postgres.ColumnList{StatusColumn, ViewsCountColumn, CommentsCountColumn, CommentsLockedColumn, CreatedAtColumn, UpdatedAtColumn, ActiveAtColumn, AttrColumn}
	)

	return postTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		CategoryID:     CategoryIDColumn,
		Title:          TitleColumn,
		AuthorID:       AuthorIDColumn,
		AuthorUsername: AuthorUsernameColumn,
		Content:        ContentColumn,
		Status:         StatusColumn,
		ViewsCount:     ViewsCountColumn,
		CommentsCount:  CommentsCountColumn,
		CommentsLocked: CommentsLockedColumn,
		PinOrder:       PinOrderColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		ActiveAt:       ActiveAtColumn,
		Attr:           AttrColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
