//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PostTag = newPostTagTable("public", "post_tag", "")

type postTagTable struct {
	postgres.Table

	// Columns
	PostID    postgres.ColumnInteger
	TagID     postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PostTagTable struct {
	postTagTable

	EXCLUDED postTagTable
}

// AS creates new PostTagTable with assigned alias
func (a PostTagTable) AS(alias string) *PostTagTable {
	return newPostTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PostTagTable with assigned schema name
func (a PostTagTable) FromSchema(schemaName string) *PostTagTable {
	return newPostTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PostTagTable with assigned table prefix
func (a PostTagTable) WithPrefix(prefix string) *PostTagTable {
	return newPostTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PostTagTable with assigned table suffix
func (a PostTagTable) WithSuffix(suffix string) *PostTagTable {
	return newPostTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPostTagTable(schemaName, tableName, alias string) *PostTagTable {
	return &PostTagTable{
		postTagTable: newPostTagTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPostTagTableImpl("", "excluded", ""),
	}
}

func newPostTagTableImpl(schemaName, tableName, alias string) postTagTable {
	var (
		PostIDColumn    = postgres.IntegerColumn("post_id")
		TagIDColumn     = postgres.IntegerColumn("tag_id")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{PostIDColumn, TagIDColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return postTagTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PostID:    PostIDColumn,
		TagID:     TagIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
