//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tag = newTagTable("public", "tag", "")

type tagTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	CategoryID postgres.ColumnInteger
	Name       postgres.ColumnString
	Color      postgres.ColumnInteger // 预定义颜色的编号
	IsActive   postgres.ColumnBool    // true=可用于新帖绑定；false=停止新增绑定
	SortOrder  postgres.ColumnInteger // 标签展示顺序，数值越小越靠前
	CreatedAt  postgres.ColumnTimestampz
	UpdatedAt  postgres.ColumnTimestampz
	Attr       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TagTable struct {
	tagTable

	EXCLUDED tagTable
}

// AS creates new TagTable with assigned alias
func (a TagTable) AS(alias string) *TagTable {
	return newTagTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TagTable with assigned schema name
func (a TagTable) FromSchema(schemaName string) *TagTable {
	return newTagTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TagTable with assigned table prefix
func (a TagTable) WithPrefix(prefix string) *TagTable {
	return newTagTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TagTable with assigned table suffix
func (a TagTable) WithSuffix(suffix string) *TagTable {
	return newTagTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTagTable(schemaName, tableName, alias string) *TagTable {
	return &TagTable{
		tagTable: newTagTableImpl(schemaName, tableName, alias),
		EXCLUDED: newTagTableImpl("", "excluded", ""),
	}
}

func newTagTableImpl(schemaName, tableName, alias string) tagTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		CategoryIDColumn = postgres.IntegerColumn("category_id")
		NameColumn       = postgres.StringColumn("name")
		ColorColumn      = postgres.IntegerColumn("color")
		IsActiveColumn   = postgres.BoolColumn("is_active")
		SortOrderColumn  = postgres.IntegerColumn("sort_order")
		CreatedAtColumn  = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampzColumn("updated_at")
		AttrColumn       = postgres.StringColumn("attr")
		allColumns       = postgres.ColumnList{IDColumn, CategoryIDColumn, NameColumn, ColorColumn, IsActiveColumn, SortOrderColumn, CreatedAtColumn, UpdatedAtColumn, AttrColumn}
		mutableColumns   = postgres.ColumnList{CategoryIDColumn, NameColumn, ColorColumn, IsActiveColumn, SortOrderColumn, CreatedAtColumn, UpdatedAtColumn, AttrColumn}
		defaultColumns   = postgres.ColumnList{IsActiveColumn, CreatedAtColumn, UpdatedAtColumn, AttrColumn}
	)

	return tagTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		CategoryID: CategoryIDColumn,
		Name:       NameColumn,
		Color:      ColorColumn,
		IsActive:   IsActiveColumn,
		SortOrder:  SortOrderColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,
		Attr:       AttrColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
